### ISSUE TITLE
System.InvalidOperationException Sequence contains no elements

### ISSUE THREAD

**Issue by OleksiiKorzhukSecurrency** [jbogard/NServiceBus.Extensions.IntegrationTesting#4]
Hi @jbogard! 

Thanks for your handy and helpful library. It has saved us a lot of time for testing.
We have faced an issue accessing the **ReceivedMessages** property without examining its emptiness.

The following test from the example works well
```csharp
 
[Fact]
public async Task Can_send_and_wait()
{
    var firstMessage = new FirstMessage {Message = "Hello World"};

    var session = _factory.Services.GetService<IMessageSession>();

    var result = await ExecuteAndWaitForHandled<FinalMessage>(() => session.SendLocal(firstMessage));

    result.IncomingMessageContexts.Count.ShouldBe(3);
    result.OutgoingMessageContexts.Count.ShouldBe(3);
    
    result.ReceivedMessages.ShouldNotBeEmpty();
    
    var message = result.ReceivedMessages.OfType<FinalMessage>().Single();

    message.Message.ShouldBe(firstMessage.Message);
}
```

But if we remove the following lines from the test 
```csharp
result.IncomingMessageContexts.Count.ShouldBe(3);
result.OutgoingMessageContexts.Count.ShouldBe(3);
    
result.ReceivedMessages.ShouldNotBeEmpty();
``` 
we will receive the following error
```
System.InvalidOperationException
Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at ***. ***.IntegrationTests.HostApplicationFactoryTests.Can_send_and_wait()
```

We have found out that if we add ```await.Task.Delay(TimeSpan.FromMilissecond(1)) ``` everything works as in the original example.
```csharp
[Fact]
public async Task Can_send_and_wait()
{
    var firstMessage = new FirstMessage {Message = "Hello World"};

    var session = _factory.Services.GetService<IMessageSession>();

    var result = await ExecuteAndWaitForHandled<FinalMessage>(() => session.SendLocal(firstMessage));

    await Task.Delay(TimeSpan.FromMilliseconds(1));
    
    var message = result.ReceivedMessages.OfType<FinalMessage>().Single();

    message.Message.ShouldBe(firstMessage.Message);
}
```

Is it expected behavior?
If not, do you have any thoughts or suggestions on where we should start the investigation of this issue? 
We would like to help with it.

**Comment by robbaman** [comment]
I have a question/remark that may be related. Looking at the diagnostics package that handles the Activity stuff, you can see that the diagnostic messages are only set AFTER the handlers are processed. This makes sense for diagnostic purposes, but when you look at what the `ExecuteAndWaitForHandled` does internally it relies on this check:

```
var finalObs = obs.Cast<TMessageContext>().TakeUntil(predicate);
```

Where the predicate is the check if the message is of the requested type. 

Because this terminates the observable that is waited on, this also means that additional diagnostic messages are no longer waited for. In particular, the diagnostic message that indicates that the handler that generated the `FinalMessage` was executed is often/always not processed in time.

I assume that either counting the lists or prerforming a 

```
await Task.Delay(TimeSpan.FromMilliseconds(1));
```

Gives the system just enough time to handle those last messages.
